// app/main/src/components/HomePage.tsx
import { useEffect, useMemo } from 'react'
import { listen } from '@tauri-apps/api/event'
import { invoke } from '@tauri-apps/api/core'
import { getVersion } from '@tauri-apps/api/app'
import { getCurrentWindow } from '@tauri-apps/api/window'
import { getStore } from '@tauri-apps/plugin-store'
import {
	isPermissionGranted,
	requestPermission,
} from '@tauri-apps/plugin-notification'
import { open } from '@tauri-apps/plugin-shell'
import { writeText } from '@tauri-apps/plugin-clipboard-manager'
import { toast } from 'sonner'
import type { ChannelMessage } from '@swarnimcodes/fero-core/bindings/ChannelMessage'
import type { EndpointInfo } from '@swarnimcodes/fero-core/bindings/EndpointInfo'
import type { OutboundPayload } from '@swarnimcodes/fero-core/bindings/OutboundPayload'
import { useAppStore } from '../lib/store/appStore'
import {
	applyAutoStart,
	clearSending,
	computeDisplayedItems,
	getDownloadPath,
	getLatestVersion,
	getRealclose,
	getStartMinimized,
	getVisibility,
	sendCmd,
	sendInfo,
	setAutoStart,
} from '../lib/utils'
import { autostartKey } from '../lib/types'
import type { DisplayedItem } from '../lib/types'
import SettingsModal from './SettingsModal'
import Heading from './Heading'
import SideMenu from './SideMenu'
import ContentStatus from './ContentStatus'
import ItemSide from './ItemSide'

export default function HomePage() {
	const {
		setStore,
		addUnlistener,
		clearUnlisteners,
		setHostname,
		setVersion,
		upsertRequest,
		removeRequest,
		pushToDelete,
		upsertEndpointInfo,
		removeEndpointInfo,
		setOutboundPayload,
		setDiscoveryRunning,
		setIsDragHovering,
		setSettingsOpen,
	} = useAppStore()

	const requests = useAppStore((s) => s.requests)
	const endpointsInfo = useAppStore((s) => s.endpointsInfo)
	const isDragHovering = useAppStore((s) => s.isDragHovering)

	// ── One-time app initialisation ──────────────────────────────────────────
	useEffect(() => {
		async function init() {
			// Tauri persisted store
			const tauriStore = (await getStore('.settings.json'))!
			setStore(tauriStore)

			// Basic app info
			const [hostname, version] = await Promise.all([
				invoke<string>('get_hostname'),
				getVersion(),
			])
			setHostname(hostname)
			setVersion(version)

			// Settings
			await getVisibility()
			if (!(await tauriStore.has(autostartKey))) {
				await setAutoStart(true)
			} else {
				await applyAutoStart()
			}
			await getRealclose()
			await getStartMinimized()
			await getDownloadPath()

			// Notification permission
			let permissionGranted = await isPermissionGranted()
			if (!permissionGranted) {
				const permission = await requestPermission()
				permissionGranted = permission === 'granted'
			}

			// ── Event: channel message ────────────────────────────────────────
			addUnlistener(
				await listen('rs2js_channelmessage', async (event) => {
					const cm = event.payload as ChannelMessage

					if (cm.state === 'Disconnected') {
						pushToDelete({ id: cm.id, triggered: Date.now() })
					}

					// Auto-clear sidebar when an outbound transfer finishes
					if (cm.state === 'Finished' && cm.rtype === 'Outbound') {
						toast.success('Sent successfully')
						useAppStore.getState().removeRequest(cm.id)
						await clearSending()
						return
					}

					upsertRequest(cm)
				}),
			)

			// ── Event: endpoint info ──────────────────────────────────────────
			addUnlistener(
				await listen('rs2js_endpointinfo', (event) => {
					const ei = event.payload as EndpointInfo
					if (!ei.present) {
						removeEndpointInfo(ei.id)
						return
					}
					upsertEndpointInfo(ei)
				}),
			)

			// ── Event: visibility changed ─────────────────────────────────────
			addUnlistener(
				await listen('visibility_updated', async () => {
					console.log('Visibility changed')
					await getVisibility()
				}),
			)

			// ── Drag-and-drop ─────────────────────────────────────────────────
			addUnlistener(
				await getCurrentWindow().onDragDropEvent(async (event) => {
					if (event.payload.type === 'over') {
						setIsDragHovering(true)
					} else if (event.payload.type === 'drop') {
						setIsDragHovering(false)
						setOutboundPayload({ Files: event.payload.paths } as OutboundPayload)
						const { discoveryRunning } = useAppStore.getState()
						if (!discoveryRunning) await invoke('start_discovery')
						setDiscoveryRunning(true)
					} else {
						setIsDragHovering(false)
					}
				}),
			)

			// Check for updates
			await getLatestVersion(version)
		}

		init()

		// Cleanup: stop all Tauri event listeners
		return () => {
			const { unlisteners } = useAppStore.getState()
			unlisteners.forEach((fn) => fn())
			clearUnlisteners()
		}
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [])

	// ── Derived state ────────────────────────────────────────────────────────
	const displayedItems: DisplayedItem[] = useMemo(
		() => computeDisplayedItems(endpointsInfo, requests),
		[endpointsInfo, requests],
	)

	// ── Helpers ───────────────────────────────────────────────────────────────
	async function writeToClipboard(text: string | undefined) {
		if (!text) return
		try {
			await writeText(text)
			toast.success('Copied to clipboard')
		} catch {
			toast.error('Unknown error while copying text')
		}
	}

	async function openUrl(url: string | undefined) {
		if (!url) return
		try {
			await open(url)
		} catch {
			toast.error('Error opening URL, it may not be a valid URI')
		}
	}

	// ── Render ───────────────────────────────────────────────────────────────
	return (
		<div className="flex flex-col w-full h-full bg-green-50 max-w-full max-h-full overflow-hidden">
			<SettingsModal />

			<Heading onOpenSettings={() => setSettingsOpen(true)} />

			<div className="flex-1 flex flex-row">
				<SideMenu />

				<div
					className={`flex-1 flex flex-col bg-white w-full max-w-full min-w-0 min-h-full rounded-tl-[3rem] p-12 h-1 overflow-y-scroll transition duration-150 ease-in-out ${isDragHovering ? 'ring-2 ring-green-300' : ''}`}
				>
					<ContentStatus />

					{displayedItems.map((item) => (
						<div
							key={item.id}
							className={`w-full rounded-3xl flex flex-row gap-6 p-4 mb-4 bg-green-100 ${item.endpoint ? 'cursor-pointer' : ''}`}
							onClick={() => item.endpoint && sendInfo(item.id)}
						>
							{/* Device icon + progress arc + pin code */}
							<ItemSide item={item} />

							{/* Transfer content and actions */}
							<div
								className={`flex-1 flex flex-col text-sm min-w-0 ${item.state === undefined ? 'justify-center' : ''}`}
							>
								<h4 className="text-base font-medium">{item.name}</h4>

								{/* ── Waiting for consent ── */}
								{item.state === 'WaitingForUserConsent' && (
									<div className="flex-1 flex flex-col justify-between">
										<p className="mt-4">
											Wants to share{' '}
											{item.files?.join(', ') ?? item.text_description ?? 'some file(s).'}
										</p>
										<div className="flex flex-row justify-end gap-4 mt-1">
											<button
												onClick={(e) => { e.stopPropagation(); sendCmd(item.id, 'AcceptTransfer') }}
												className="btn px-3 rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none"
											>
												Accept
											</button>
											<button
												onClick={(e) => { e.stopPropagation(); sendCmd(item.id, 'RejectTransfer') }}
												className="btn px-3 rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none"
											>
												Decline
											</button>
										</div>
									</div>
								)}

								{/* ── In progress ── */}
								{['SentIntroduction', 'SendingFiles', 'ReceivingFiles'].includes(
									item.state ?? '',
								) && (
									<div>
										{['SentIntroduction', 'SendingFiles'].includes(item.state ?? '') ? (
											<p className="mt-2">Sending...</p>
										) : (
											<p className="mt-2">Receiving...</p>
										)}
										{item.files?.map((f) => (
											<p key={f} className="overflow-hidden whitespace-nowrap text-ellipsis">
												{f}
											</p>
										))}
										<div className="flex flex-row justify-end gap-4 mt-1">
											<button
												onClick={(e) => { e.stopPropagation(); sendCmd(item.id, 'CancelTransfer') }}
												className="btn px-3 rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none"
											>
												Cancel
											</button>
										</div>
									</div>
								)}

								{/* ── Finished outbound ── */}
								{item.state === 'Finished' && item.rtype === 'Outbound' && (
									<div>
										<p className="mt-2">Sent successfully</p>
										<div className="flex flex-row justify-end gap-4 mt-1">
											<button
												onClick={(e) => { e.stopPropagation(); removeRequest(item.id) }}
												className="btn px-3 rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none"
											>
												Clear
											</button>
										</div>
									</div>
								)}

								{/* ── Finished inbound ── */}
								{item.state === 'Finished' && item.rtype !== 'Outbound' && (
									<div>
										<p className="mt-2">Received {item.text_type ? 'text' : ''}</p>
										{item.files?.map((f) => (
											<p key={f} className="overflow-hidden whitespace-nowrap text-ellipsis">
												{f}
											</p>
										))}
										{item.files && (
											<p className="mt-2 overflow-hidden whitespace-nowrap text-ellipsis">
												Saved to {item.destination}
											</p>
										)}
										{item.text_type && (
											<p className="select-text cursor-text overflow-hidden whitespace-nowrap text-ellipsis">
												{item.text_payload}
											</p>
										)}
										<div className="flex flex-row justify-end gap-4 mt-1">
											{(item.destination ||
												(item.text_type === 'Url' && item.text_payload)) && (
												<button
													onClick={(e) => {
														e.stopPropagation()
														openUrl(item.destination ?? item.text_payload)
													}}
													className="btn px-3 rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none"
												>
													Open
												</button>
											)}
											{item.text_type && item.text_payload && (
												<button
													onClick={(e) => {
														e.stopPropagation()
														writeToClipboard(item.text_payload)
													}}
													className="btn px-3 rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none"
												>
													Copy
												</button>
											)}
											<button
												onClick={(e) => {
													e.stopPropagation()
													removeRequest(item.id)
												}}
												className="btn px-3 rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none"
											>
												Clear
											</button>
										</div>
									</div>
								)}

								{/* ── Cancelled ── */}
								{item.state === 'Cancelled' && (
									<div>
										<p className="mt-2">Transfer cancelled</p>
										<div className="flex flex-row justify-end gap-4 mt-1">
											<button
												onClick={(e) => { e.stopPropagation(); removeRequest(item.id) }}
												className="btn px-3 rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none"
											>
												Clear
											</button>
										</div>
									</div>
								)}

								{/* ── Rejected ── */}
								{item.state === 'Rejected' && (
									<div>
										<p className="mt-2">Transfer rejected</p>
										<div className="flex flex-row justify-end gap-4 mt-1">
											<button
												onClick={(e) => { e.stopPropagation(); removeRequest(item.id) }}
												className="btn px-3 rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none"
											>
												Clear
											</button>
										</div>
									</div>
								)}

								{/* ── Disconnected ── */}
								{item.state === 'Disconnected' && (
									<div>
										<p className="mt-2">Unexpected disconnection</p>
										<div className="flex flex-row justify-end gap-4 mt-1">
											<button
												onClick={(e) => { e.stopPropagation(); removeRequest(item.id) }}
												className="btn px-3 rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none"
											>
												Clear
											</button>
										</div>
									</div>
								)}
							</div>
						</div>
					))}
				</div>
			</div>
		</div>
	)
}

// app/main/src/components/HomePage.vue
<template>
	<div class="flex flex-col w-full h-full bg-green-50 max-w-full max-h-full overflow-hidden">
		<ToastNotification />
		<SettingsModal :vm="vm" @close="settingsOpen = false" />

		<Heading :vm="vm" :open-url="openUrl" @open-settings="settingsOpen = true" />

		<div class="flex-1 flex flex-row">
			<SideMenu :vm="vm" @invert-visibility="invertVisibility(vm)" @clear-sending="clearSending(vm)" />

			<div class="flex-1 flex flex-col bg-white w-full max-w-full min-w-0 min-h-full rounded-tl-[3rem] p-12 h-1 overflow-y-scroll">
				<ContentStatus :vm="vm" @outbound-payload="(el: OutboundPayload) => outboundPayload = el" @discovery-running="discoveryRunning = true;" />

				<div
					v-for="item in displayedItems" :key="item.id" class="w-full rounded-3xl flex flex-row gap-6 p-4 mb-4 bg-green-100"
					:class="{'cursor-pointer': item.endpoint}" @click="item.endpoint && sendInfo(vm, item.id)">
					<!-- Loader and image of the device type & pin_code -->
					<ItemSide :item="item" />

					<!-- Content and state of the transfer -->
					<div class="flex-1 flex flex-col text-sm min-w-0" :class="{'justify-center': item.state === undefined}">
						<h4 class="text-base font-medium">
							{{ item.name }}
						</h4>

						<div v-if="item.state === 'WaitingForUserConsent'" class="flex-1 flex flex-col justify-between">
							<p class="mt-4">
								Wants to share {{ item.files?.join(', ') ?? item.text_description ?? 'some file(s).' }}
							</p>
							<div class="flex flex-row justify-end gap-4 mt-1">
								<p
									@click.stop="sendCmd(vm, item.id, 'AcceptTransfer')" class="btn px-3
									rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none">
									Accept
								</p>
								<p
									@click.stop="sendCmd(vm, item.id, 'RejectTransfer')" class="btn px-3
									rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none">
									Decline
								</p>
							</div>
						</div>

						<div v-else-if="['SentIntroduction', 'SendingFiles', 'ReceivingFiles'].includes(item.state ?? 'Initial')">
							<p class="mt-2" v-if="['SentIntroduction', 'SendingFiles'].includes(item.state ?? 'Initial')">
								Sending...
							</p>
							<p class="mt-2" v-else>
								Receiving...
							</p>
							<p v-for="f in item.files ?? []" :key="f" class="overflow-hidden whitespace-nowrap text-ellipsis">
								{{ f }}
							</p>
							<div class="flex flex-row justify-end gap-4 mt-1">
								<p
									@click.stop="sendCmd(vm, item.id, 'CancelTransfer')" class="btn px-3
									rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none">
									Cancel
								</p>
							</div>
						</div>

						<div v-else-if="item.state === 'Finished' && item.rtype === 'Outbound'">
							<p class="mt-2">
								Sent successfully
							</p>
							<div class="flex flex-row justify-end gap-4 mt-1">
								<p
									@click.stop="removeRequest(vm, item.id)"
									class="btn px-3 rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none">
									Clear
								</p>
							</div>
						</div>

						<div v-else-if="item.state === 'Finished'">
							<p class="mt-2">
								Received <span v-if="item.text_type">text</span>
							</p>

							<!-- If files -->
							<p v-for="f in item.files ?? []" :key="f" class="overflow-hidden whitespace-nowrap text-ellipsis">
								{{ f }}
							</p>
							<p v-if="item.files" class="mt-2 overflow-hidden whitespace-nowrap text-ellipsis">
								<span v-if="item.files">Saved to </span>{{ item.destination }}
							</p>

							<!-- If text -->
							<p v-if="item.text_type" class="!select-text cursor-text overflow-hidden whitespace-nowrap text-ellipsis">
								{{ item.text_payload }}
							</p>

							<div class="flex flex-row justify-end gap-4 mt-1">
								<p
									v-if="item.destination || (item.text_type === 'Url' && item.text_payload)"
									@click.stop="openUrl(item.destination ?? item.text_payload!)"
									class="btn px-3 rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none">
									Open
								</p>
								<p
									v-if="item.text_type && item.text_payload" @click.stop="writeToClipboard(item.text_payload)"
									class="btn px-3 rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none">
									Copy
								</p>
								<p
									@click.stop="removeRequest(vm, item.id)"
									class="btn px-3 rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none">
									Clear
								</p>
							</div>
						</div>

						<div v-else-if="item.state === 'Cancelled'">
							<p class="mt-2">
								Transfer cancelled
							</p>
							<div class="flex flex-row justify-end gap-4 mt-1">
								<p
									@click.stop="removeRequest(vm, item.id)" class="btn px-3
									rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none">
									Clear
								</p>
							</div>
						</div>

						<div v-else-if="item.state === 'Rejected'">
							<p class="mt-2">
								Transfer rejected
							</p>
							<div class="flex flex-row justify-end gap-4 mt-1">
								<p
									@click.stop="removeRequest(vm, item.id)" class="btn px-3
									rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none">
									Clear
								</p>
							</div>
						</div>

						<div v-else-if="item.state === 'Disconnected'">
							<p class="mt-2">
								Unexpected disconnection
							</p>
							<div class="flex flex-row justify-end gap-4 mt-1">
								<p
									@click.stop="removeRequest(vm, item.id)" class="btn px-3
									rounded-xl active:scale-95 transition duration-150 ease-in-out shadow-none">
									Clear
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>

<script lang="ts">
import { ref, nextTick } from 'vue'
import { UnlistenFn, listen } from '@tauri-apps/api/event'
import { invoke } from '@tauri-apps/api/core'
import { getVersion } from '@tauri-apps/api/app';
import { getCurrentWindow } from '@tauri-apps/api/window';
import { getStore } from "@tauri-apps/plugin-store";
import { isPermissionGranted, requestPermission } from '@tauri-apps/plugin-notification';
import { disable, enable } from '@tauri-apps/plugin-autostart';
import { open as tauriDialog } from '@tauri-apps/plugin-dialog';
import { open } from '@tauri-apps/plugin-shell';
import { writeText } from '@tauri-apps/plugin-clipboard-manager';

import { ChannelMessage } from '@swarnimcodes/fero-lib/bindings/ChannelMessage';
import { EndpointInfo } from '@swarnimcodes/fero-lib/bindings/EndpointInfo';
import { OutboundPayload } from '@swarnimcodes/fero-lib/bindings/OutboundPayload';
import { Visibility } from '@swarnimcodes/fero-lib/bindings/Visibility';

import { ToastNotification, ToDelete, stateToDisplay, autostartKey, DisplayedItem, useToastStore, opt, ToastType, utils } from '../vue_lib';

import SettingsModal from '../composables/SettingsModal.vue';
import Heading from '../composables/Heading.vue';
import SideMenu from '../composables/SideMenu.vue';
import ContentStatus from '../composables/ContentStatus.vue';
import ItemSide from '../composables/ItemSide.vue';

export default {
	name: "HomePage",

	components: {
		ToastNotification,
		SettingsModal,
		Heading,
		SideMenu,
		ContentStatus,
		ItemSide
	},

	async setup() {
		const store = (await getStore(".settings.json"))!;
		const toastStore = useToastStore();

		const dialogOpen = tauriDialog;

		return {
			stateToDisplay,
			store,
			toastStore,
			invoke,
			getVersion,
			enable,
			disable,
			dialogOpen,
			...utils
		};
	},

	data() {
		return {
			isAppInForeground: false,
			discoveryRunning: ref(false),
			isDragHovering: ref(false),

			requests: ref<ChannelMessage[]>([]),
			endpointsInfo: ref<EndpointInfo[]>([]),
			toDelete: ref<ToDelete[]>([]),
			outboundPayload: ref<OutboundPayload | undefined>(),

			// eslint-disable-next-line no-undef
			cleanupInterval: opt<NodeJS.Timeout>(),
			unlisten: Array<UnlistenFn>(),

			version: opt<string>(),

			autostart: ref<boolean>(true),
			realclose: ref<boolean>(false),
			startminimized: ref<boolean>(false),
			visibility: ref<Visibility>('Visible'),
			downloadPath: ref<string | undefined>(),

			hostname: ref<string>(),

			settingsOpen: ref<boolean>(false),

			new_version: opt<string>(),
		};
	},

	mounted: function () {
		nextTick(async () => {
			this.hostname = await invoke('get_hostname');
			this.version = await getVersion();

			await this.getVisibility(this);

			if (!await this.store.has(autostartKey)) {
				await this.setAutoStart(this, true);
			} else {
				await this.applyAutoStart(this);
			}

			await this.getRealclose(this);
			await this.getStartMinimized(this);
			await this.getDownloadPath(this);

			// Check permission for notification
			let permissionGranted = await isPermissionGranted();
			if (!permissionGranted) {
				const permission = await requestPermission();
				permissionGranted = permission === 'granted';
			}

			this.unlisten.push(
				await listen('rs2js_channelmessage', async (event) => {
					const cm = event.payload as ChannelMessage;
					const idx = this.requests.findIndex((el) => el.id === cm.id);

					if (cm.state === "Disconnected") {
						this.toDelete.push({
							id: cm.id,
							triggered: new Date().getTime()
						});
					}

					// Auto-reset sidebar and remove card when an outbound transfer completes
					if (cm.state === "Finished" && cm.rtype === "Outbound") {
						this.toastStore.addToast("Sent successfully", ToastType.Success);
						const finIdx = this.requests.findIndex((el) => el.id === cm.id);
						if (finIdx !== -1) this.requests.splice(finIdx, 1);
						await this.clearSending(this);
						return;
					}

					if (idx !== -1) {
						const prev = this.requests.at(idx);
						// Update the existing message at index 'idx'
						this.requests.splice(idx, 1, {
							...cm,
							state: cm.state ?? prev!.state,
							meta: cm.meta ?? prev!.meta,
						});
					} else {
						// Push the new message if not found
						this.requests.push(cm);
					}

					return;
				})
			);

			this.unlisten.push(
				await listen('rs2js_endpointinfo', (event) => {
					const ei = event.payload as EndpointInfo;
					const idx = this.endpointsInfo.findIndex((el) => el.id === ei.id);

					if (!ei.present) {
						if (idx !== -1) {
							this.endpointsInfo.splice(idx, 1);
						}

						return;
					}

					if (idx !== -1) {
						this.endpointsInfo.splice(idx, 1, ei);
					} else {
						this.endpointsInfo.push(ei);
					}
				})
			);

			this.unlisten.push(
				await listen('visibility_updated', async () => {
					console.log("Visibility changed");
					await this.getVisibility(this);
				})
			);

			this.unlisten.push(
				await getCurrentWindow().onDragDropEvent(async (event) => {
					if (event.payload.type === 'over') {
						this.isDragHovering = true;
					} else if (event.payload.type === 'drop') {
						console.log("Dropped");
						this.isDragHovering = false;
						this.outboundPayload = {
							Files: event.payload.paths
						} as OutboundPayload;
						if (!this.discoveryRunning) await invoke('start_discovery');
						this.discoveryRunning = true;
					} else {
						this.isDragHovering = false;
					}
				})
			);

			await this.getLatestVersion(this);
		});
	},

	unmounted: function() {
		this.unlisten.forEach((el) => el());

		if (this.cleanupInterval && this.cleanupInterval[Symbol.dispose]) {
			this.cleanupInterval[Symbol.dispose]();
		}
	},

	computed: {
		vm() {
			return this;
		},
		displayedIsEmpty(): boolean {
			return this.displayedItems.length == 0
		},
		displayedItems(): Array<DisplayedItem> {
			return this._displayedItems(this);
		}
	},

	methods: {
		writeToClipboard: async function(text: string) {
			try {
				await writeText(text);
				this.toastStore.addToast("Copied to clipboard", ToastType.Success);
			} catch (e) {
				this.toastStore.addToast("Unknown error while copying text", ToastType.Error);
				console.error("Error copying text", e);
			}
		},
		openUrl: async function(url: string) {
			try {
				await open(url);
			} catch (e) {
				this.toastStore.addToast("Error opening URL, it may not be a valid URI", ToastType.Error);
				console.error("Error opening URL", e);
			}
		},
	},
}
</script>
